version: '2'
services:
  nodered:
    build:
      context: .
    restart: always
    group_add:
      - dialout
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    environment:
      - MQTT_SERVER
