version: '2.4'
services:
  nodered:
    build:
      context: .
    restart: always
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/gpiomem:/dev/gpiomem"
    ports:
      - "1880:1880"
    environment:
      - MODE_TIC
      - SERIAL_BAUDRATE
      - MQTT_SERVER
      - MQTT_PORT
